name          'thejandroman-nzbget'
version       '0.1.0'
source        ''
author        'thejandroman'
license       'Apache-2.0'
summary       'Install and configure nzbget'
description   ''
project_page  ''

dependency 'puppetlabs/stdlib'
dependency 'maestrodev/wget'
dependency 'puppetlabs/concat'
